EducationalServices/Models/DriverAssignment.cs
// EducationalServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// EducationalServices.Models.DriverAssignment
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EducationalServices.Models;
using PayPal.Api;

public class DriverAssignment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AssDrivId { get; set; }

    [DisplayName("Order Number")]
    public int OrderId { get; set; }

    public int DrivId { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Email { get; set; }

    public string Status { get; set; }

    [DataType(DataType.Date)]
    public string DeliveryDate { get; set; }

    [DataType(DataType.Time)]
    public string DeliveryTime { get; set; }

    public DateTime Created { get; set; }

    public bool IsActive { get; set; }

    [DisplayName("Due on")]
    public string GenDeliveryDate { get; set; }

    [DisplayName("Selected Time")]
    public string preffaredTime { get; set; }

    [DisplayName("Delivery Address")]
    public string DeliveryAddress { get; set; }

    [ForeignKey("OrderId")]
    public virtual Orders Orders { get; set; }

    [ForeignKey("DrivId")]
    public virtual Driver Driver { get; set; }
}

EducationalServices/Controllers/DriverAssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;

using EducationalServices.Models;
using iTextSharp.text.pdf;
using iTextSharp.text;
using static iTextSharp.text.TabStop;
using Org.BouncyCastle.Asn1.X509;
using System.Deployment.Internal;


namespace EducationalServices.Controllers
{
    public class DriverAssignmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DriverAssignments
        public ActionResult Index()
        {
            var driverAssignments = db.DriverAssignments.Include(d => d.Driver).Include(d => d.Orders);
            return View(driverAssignments.ToList());
        }
        public ActionResult MyAssignments(string email = "Email")
        {
            if (email == "Email")
            {
                email = User.Identity.Name;
                ViewBag.Title = "Assignments";
            }
            else
            {
                ViewBag.Title = email+"'s Assignments";
            }
            var driverAssignments = db.DriverAssignments.Include(d => d.Driver).Include(d => d.Orders).Where(x=>x.Driver.Email == email);
            return View(driverAssignments.ToList());
        }


            public ActionResult OrderReady(int id)
        {
            var assignment = db.DriverAssignments.Find(id);
            var order = db.Orders.Find(assignment.OrderId);
            assignment.Status = "Ready for pickup";
            order.Status = "Ready for pickup";
            db.Entry(assignment).State = EntityState.Modified;
            db.Entry(order).State = EntityState.Modified;

            try
            {
                // Prepare email message
                var email2 = new MailMessage();
                email2.From = new MailAddress("Poultry.dbn@outlook.com");
                email2.To.Add(assignment.Email);
                email2.Subject = "Order Ready |  " + assignment.OrderId;
                string emailBody = $"Order Number: " + assignment.OrderId + "\t\tDelivery Date: " + assignment.DeliveryDate + "\t\t Delivery Time: " + assignment.DeliveryTime + " \n\n" +
               $"Hi {assignment.Driver.Name}, \n\n" +
               $"Please note that, order {assignment.OrderId} is ready to be picked up for delivery to address {assignment.Orders.Address}, please procced with order delivery within due time.\n\n" +



               $"Regards,\r\nEducational Services";
                email2.Body = emailBody;


                var smtpClient = new SmtpClient();

                smtpClient.Send(email2);

            }
            catch (Exception ex)
            {
                TempData["Message"] = "Failed to send email due to, " + ex.Message;
                return RedirectToAction("Index");
            }
            db.SaveChanges();
            TempData["Message"] = "Order Successfully Marked as Ready for Delivery";
            return RedirectToAction("Index");
        }

        public ActionResult DispatchOrder(int id)
        {
            var ass = db.DriverAssignments.Where(x=>x.OrderId == id).FirstOrDefault();
            var order = db.Orders.Find(ass.OrderId);
            order.Status = "PikingUp";
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            DispatchRecord b = new DispatchRecord()
            {
                OrderNumber = id,
                AssDrivId = ass.AssDrivId,
                DriverName = ass.Driver.Name,
                DriverSurnane = ass.Driver.Surname

            };
            return View(b);
        }
        [HttpPost]
        public ActionResult DispatchOrder(DispatchRecord dispatchRecords)
        {
            string base64Signature = dispatchRecords.Signature;

            string signatureImagePath = SaveSignatureImage(base64Signature);
            string folderPath = Server.MapPath("~/App_Data/");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            string fileName = $"Document-{DateTime.Now:yyyyMMddHHmmss}.pdf";
            string filePath = Path.Combine(folderPath, fileName);
            CreatePdfWithSignature(signatureImagePath, filePath, dispatchRecords.AssDrivId);


            var ass = db.DriverAssignments.Find(dispatchRecords.AssDrivId);
            var order = db.Orders.Find(ass.OrderId);
            ass.Status = "PickedUp";
            order.Status = "PickedUp";
            order.PickupDate = DateTime.Now;
            string recipientEmail = ass.Driver.Email;
            db.Entry(ass).State = EntityState.Modified;
            db.Entry(order).State = EntityState.Modified;

            SendPdfEmail(recipientEmail, filePath);


            dispatchRecords.filePath = filePath;
            db.DispatchRecords.Add(dispatchRecords);
        

            db.SaveChanges();
            return View(dispatchRecords);
        }
        private void CreatePdfWithSignature(string signatureImagePath, string filePath, int id)
        {
            var ass = db.DriverAssignments.Find(id);
            
            
            using (FileStream fileStream = new FileStream(filePath, FileMode.Create, FileAccess.Write))
            {
                Document document = new Document(PageSize.A4, 25, 25, 30, 30);
                PdfWriter.GetInstance(document, fileStream);
                document.Open();

                
                Font titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLACK);
                Font subtitleFont = FontFactory.GetFont(FontFactory.HELVETICA, 14, BaseColor.DARK_GRAY);
                Font bodyFont = FontFactory.GetFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);

                
                Paragraph title = new Paragraph("Dispatch Order Record", titleFont)
                {
                    Alignment = Element.ALIGN_CENTER,
                    SpacingAfter = 10
                };
                document.Add(title);

                // Add subtitle
                Paragraph subtitle = new Paragraph("Dispatch Information", subtitleFont)
                {
                    Alignment = Element.ALIGN_CENTER,
                    SpacingAfter = 20
                };
                document.Add(subtitle);

                // Add document content
                Paragraph content1 = new Paragraph("Order Number: " + ass.OrderId, bodyFont)
                {
                    SpacingAfter = 10
                };
                Paragraph content2 = new Paragraph("Driver Name: " + ass.Driver.Name, bodyFont)
                {
                    SpacingAfter = 10
                };
                Paragraph content3 = new Paragraph("Driver Surname: " + ass.Driver.Surname, bodyFont)
                {
                    SpacingAfter = 20
                };
               
                document.Add(content1);
                document.Add(content2);
                document.Add(content3);

                Paragraph subtitle2 = new Paragraph("Delivery Information", subtitleFont)
                {
                    Alignment = Element.ALIGN_CENTER,
                    SpacingAfter = 20
                };
                document.Add(subtitle);

                Paragraph content4= new Paragraph("Delivery Date: " + ass.DeliveryDate, bodyFont)
                {
                    SpacingAfter = 10
                };
                Paragraph content5 = new Paragraph("Delivery Time: " + ass.DeliveryTime, bodyFont)
                {
                    SpacingAfter = 20
                };
                Paragraph content6 = new Paragraph("Date: " + DateTime.Now.ToShortDateString(), bodyFont)
                {
                    SpacingAfter = 10
                };
                document.Add(content4);
                document.Add(content5);
                document.Add(content6);


                // Add Signature Section as an image
                document.Add(new Paragraph("\n\nSignature:", bodyFont));

                try
                {
                    if (System.IO.File.Exists(signatureImagePath))
                    {
                        // Add signature image if it exists
                        Image signatureImage = Image.GetInstance(signatureImagePath);
                        signatureImage.ScaleToFit(200f, 80f); // Adjust the size as needed
                        signatureImage.Alignment = Element.ALIGN_LEFT; // Align as needed
                        document.Add(signatureImage);
                    }
                    else
                    {
                        document.Add(new Paragraph("Signature image not found.", bodyFont));
                    }
                }
                catch (Exception ex)
                {
                    // Handle any exceptions related to image processing
                    document.Add(new Paragraph($"Error adding signature image: {ex.Message}", bodyFont));
                }

                // Finalize the document
                document.Close();
            }
        }
        private string SaveSignatureImage(string base64Signature)
        {
            // Decode base64 string to byte array
            byte[] imageBytes = Convert.FromBase64String(base64Signature);

            // Application folder path where signature images will be saved
            string folderPath = Server.MapPath("~/App_Data/");
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            // Create file path for the signature image
            string imagePath = Path.Combine(folderPath, $"Signature-{DateTime.Now:yyyyMMddHHmmss}.png");

            // Save the byte array to the image file
            System.IO.File.WriteAllBytes(imagePath, imageBytes);

EducationalServices/Views/DriverAssignments/Delete.cshtml
@model EducationalServices.Models.DriverAssignment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DriverAssignment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Driver.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Driver.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Orders.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Orders.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenDeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenDeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.preffaredTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preffaredTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EducationalServices/Views/DriverAssignments/DispatchOrder.cshtml
@{
    ViewBag.Title = "DispatchOrder";
}

<h2>Dispatch Order</h2>

EducationalServices/Views/DriverAssignments/FinishOrderDelivery.cshtml
@{
    ViewBag.Title = "FinishOrderDelivery";
}

<h2>Complete Delivery</h2>



        
        <div id="countdown"></div>
        <form id="noResponseForm" action="@Url.Action("NoResponseAction", "DriverAssignments")" method="post">

            <button type="submit" id="submitButton" style="display: none;"></button>
        </form>
        

        <div id="manual-code-input">
            <form id="code-form" method="post" action="@Url.Action("FinishOrderDelivery", "DriverAssignments")">
                <label for="code-input">Please Enter Unique:</label>
                <input type="text" id="code-input" name="code">
                <button type="submit">Submit</button>
            </form>
        </div>
 


<script>
    // Function to update countdown timer
    function updateCountdown() {
        var countdownElement = document.getElementById('countdown');
        var minutes = Math.floor(timeLeft / 60);
        var seconds = timeLeft % 60;

        // Display remaining time in minutes and seconds
        countdownElement.innerHTML = 'Waiting Time: ' + minutes + 'm ' + seconds + 's';

        // Decrease time left by 1 second
        timeLeft--;

        // If time left is less than 0, submit the form
        if (timeLeft < 0) {
            clearInterval(timer);
            // Show the submit button before submitting the form
            document.getElementById('submitButton').style.display = 'block';
            document.getElementById('noResponseForm').submit();
        }
    }

    // Set the countdown duration in seconds (1 minute = 60 seconds)
    var duration = 600;

    // Calculate time left (in seconds)
    var timeLeft = duration;

    // Update countdown every second
    var timer = setInterval(updateCountdown, 1000);
</script>


<script>
    // Function to handle manual code submission
    function submitManualCode() {
        var manualCode = document.getElementById('code-input').value;
        if (manualCode.trim() !== '') {
            // Call a function to handle the manual code submission
            document.getElementById('code-form').submit();
        } else {
            alert('Please enter a code.');
        }
    }

    

   
</script>

EducationalServices/Views/DriverAssignments/MyAssignments.cshtml
@model IEnumerable<EducationalServices.Models.DriverAssignment>
@using EducationalServices.Models
@{
    ViewBag.Title = "MyAssignments";
    ApplicationDbContext db = new ApplicationDbContext();
}


<h2>My Assignments</h2>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

@foreach (var item in Model)
{
    <div class="container">
        <div class="main-body">
            <div class="row">

                <div class="col-lg-8">

                    <div class="card mt-4">
                        <div class="card-body p-0 table-responsive">
                            <h4 class="p-3 mb-0">Order: @item.OrderId &nbsp; Date: @item.Orders.OrderDate.ToLongDateString() </h4>
                            <table class="table mb-0">
                                <thead>
                                    <tr>
                                        <th scope="col">Description</th>
                                        <th scope="col"></th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">Amount</th>
                                        <th scope="col">Weight</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{var products = db.OrderDetails.Where(x => x.OrderId == item.OrderId).ToList();
                                    }

                                    @foreach (var prod in products)
                                    {
                                        <tr>

                                            <th>
                                                <img src="data:image;base64,@prod.Picture"
                                                     alt="product" class="" width="80">
                                            </th>
                                            <td>
                                                @prod.Name
                                            </td>
                                            <td>@prod.StockQuantity</td>
                                            <td><strong>@prod.Price.ToString("R0.00")</strong></td>

                                            <td><span class="badge badge-warning">@prod.Weight</span></td>

                                        </tr>
                                    }
                                    <tr>
                                        <th colspan="2">
                                            <span>Delivery Date: @item.DeliveryDate</span>
                                            <span>Delivery Time: @item.DeliveryTime</span>
                                            @if (item.Status == "Placed")
                                            {
                                                <span class="badge badge-success">PENDING</span>
                                            }

                                        </th>
                                        <td>
                                            <span class="text-muted">Product Cost</span>
                                            <strong>@item.Orders.ProductCost.ToString("R0.00")</strong>
                                        </td>
                                        <td>
                                            <span class="text-muted">Delivery Fee</span>
                                            <strong>@item.Orders.DeliveryFee.ToString("R0.00")</strong>
                                        </td>
                                        <td>

                                            <span class="text-muted">Total</span>
                                            <strong>@item.Orders.TotalAmount.ToString("R0.00")</strong>
                                        </td>
                                        <td>
                                            <button type="button" class="list-group-item list-group-item-action border-0 btn btn-primary" data-toggle="modal" data-target="#deliveriesModal-@item.DrivId">
                                                More info
                                            </button>
                                            <button type="button" class="list-group-item list-group-item-action border-0 btn btn-primary" data-toggle="modal" data-target="#StartDeliveryModal-@item.DrivId">
                                                Start Delivery
                                            </button>
                                            


                                            <button class="btn btn-outline-dark" style="margin-left: 5px;" onclick="location.href='@Url.Action(actionName: "Index", controllerName: "Drivers", routeValues: new { orderId = item.OrderId })'">Start Delivery</button>

                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="deliveriesModal-@item.DrivId" tabindex="-1" role="dialog" aria-labelledby="deliveriesModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deliveriesModalLabel">Assignment Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Order Number: @item.OrderId</p>
                    <p>Driver: @item.Driver.Name  @item.Driver.Surname</p>
                    <p>Driver Email: @item.Email</p>
                    <p>Delivery Date: @item.DeliveryDate</p>
                    <p>Delivery Time: @item.DeliveryTime</p>
                    <p>Assigned at: @item.Created</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="StartDeliveryModal-@item.DrivId" tabindex="-1" role="dialog" aria-labelledby="StartDeliveryModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="StartDeliveryModalLabel">Are you sure you want to start delivery for this order?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="@Url.Action("StartOrderDelivery", "DriverAssignments")" method="post">
                        <input type="hidden" id="id" name="id" value="@item.AssDrivId" required>
                        <label>Estimated Arrival Time</label>
                        <input type="text" id="estArrivalTime-@item.DrivId" name="estArrivalTime" value="" required>
                        <label>Destination</label>
                        <input type="text" id="Destination-@item.DrivId" name="Destination" value="@item.Orders.Address" required>
                        <label>Distance</label>
                        <input type="text" id="Distance-@item.DrivId" name="Distance" value="" required>
                        <label>Driving Time</label>
                        <input type="text" id="DrivingTime-@item.DrivId" name="DrivingTime" value="" required>
                        <button type="submit" class="btn btn-primary">Confirm</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}


<script>
    let userLocation = null;

    // Get current location from Geolocation API
    function getCurrentLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(position => {
                userLocation = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
            }, () => {
                alert("Geolocation permission denied or not available.");
            });
        } else {
            alert("Geolocation is not supported by this browser.");
        }
    }

    // Function to calculate travel details using the Google Maps Directions API
    function calculateTravelDetails(drivId) {
        const destinationField = document.querySelector(`#Destination-${drivId}`);
        const destination = destinationField.value;

        if (!userLocation || !destination) {
            alert("Invalid starting location or destination.");
            return;
        }

        const directionsService = new google.maps.DirectionsService();

        const request = {
            origin: userLocation,
            destination: destination,
            travelMode: 'DRIVING'
        };

        directionsService.route(request, (result, status) => {
            if (status === 'OK') {
                const route = result.routes[0].legs[0];
                // Set values to modal fields
                document.querySelector(`#estArrivalTime-${drivId}`).value = route.arrival_time ? route.arrival_time.text : "N/A";
                document.querySelector(`#Distance-${drivId}`).value = route.distance.text;
                document.querySelector(`#DrivingTime-${drivId}`).value = route.duration.text;
            } else {
                alert("Error calculating route. Please try again.");
            }
        });
    }

    // Initialize the map and user's current location
    function initMap() {
        getCurrentLocation();
    }

    // Event listener to calculate data on modal opening
    $(document).ready(function () {
        $('[id^="StartDeliveryModal-"]').on('shown.bs.modal', function (event) {
            // Extract drivId from the modal id
            const drivId = $(this).attr('id').split('-')[1];
            calculateTravelDetails(drivId);
        });
    });
</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous">
</script>

EducationalServices/Views/DriverAssignments/Navigation.cshtml
@{
    ViewBag.Title = "Navigation";
}
<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>


<div class="container py-md-5 py-2">
    <h2>Goole Maps</h2>
    <div id="map"></div>
    
    <a href="@Url.Action("FinishOrderDelivery","DriverAssignments")" class="btn btn-warning" data-abc="true"> Finish Delivery</a>
</div>

<script>
        var map;
        var directionsService;
        var directionsRenderer;
        var carMarker;

        function initMap() {
            // Initialize the map
            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 8,
                center: { lat: -34.397, lng: 150.644 } // Default center
            });

            directionsService = new google.maps.DirectionsService();
            directionsRenderer = new google.maps.DirectionsRenderer({
                map: map,
                panel: document.getElementById('directions-panel') // Display route steps in this panel
            });

            // Get user's current location
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function (position) {
                    var userLocation = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                    };

                    // Fetch destination address from ViewBag and convert to string
                    var destinationAddress = '@ViewBag.DestinationAddress';

                    // Calculate route between user's location and destination
                    var request = {
                        origin: userLocation,
                        destination: destinationAddress,
                        travelMode: google.maps.TravelMode.DRIVING
                    };

                    directionsService.route(request, function (response, status) {
                        if (status == google.maps.DirectionsStatus.OK) {
                            directionsRenderer.setDirections(response);
                            // Start updating car icon position
                            updateCarPosition(response.routes[0].legs[0].steps, 0);
                        } else {
                            console.error('Error calculating directions:', status);
                        }
                    });
                });
            } else {
                console.error('Geolocation is not supported by this browser.');
            }
        }

        function updateCarPosition(steps, stepIndex) {
            var step = steps[stepIndex];
            var stepPath = step.path;
            var carIndex = 0;
            carMarker = new google.maps.Marker({
                map: map,
                icon: {
                    url: 'car-icon.png', // Replace with the path to your car icon
                    scaledSize: new google.maps.Size(50, 50) // Adjust the size of the icon
                }
            });

            setInterval(function () {
                carIndex++;
                if (carIndex >= stepPath.length) {
                    if (stepIndex + 1 < steps.length) {
                        stepIndex++;
                        step = steps[stepIndex];
                        stepPath = step.path;
                        carIndex = 0;
                    } else {
                        return; // Reached end of route
                    }
                }
                carMarker.setPosition(stepPath[carIndex]);
            }, 1000); // Update car position every 1 second (adjust as needed)
        }
</script>

<!-- Include Google Maps API script with the callback parameter -->
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqHXPxdgr3xi02C7qEDoYjSHpgBZ-WL0g&callback=initMap&callback=initMap"></script>